apiVersion: v1
kind: Pod
metadata:
  name: "my-pod-webserver"
  labels:
    name: "my-pod-webserver"
spec:
  containers:
  - name: "my-container"
    image: "docker-registry.default.svc:5000/openshift/httpd"
    ports:
    - containerPort: 80
      protocol: TCP

